# Generated by Django 5.2 on 2025-04-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_generalsettings_generalsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalsetting',
            old_name='parameters',
            new_name='parameter',
        ),
    ]
