# Generated by Django 5.2 on 2025-04-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order',), 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
