# Generated by Django 5.2 on 2025-04-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_skill_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('Degree_name', models.CharField(blank=True, default='', max_length=254, verbose_name='Degree Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default='None', null=True, verbose_name='End Date')),
                ('school_location', models.CharField(blank=True, default='', help_text='School Name , Location', max_length=254, verbose_name='School Location')),
                ('parameter', models.CharField(blank=True, default='', verbose_name='Parameter')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ('start_date',),
            },
        ),
    ]
