# Generated by Django 5.2 on 2025-04-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sumary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name_surname', models.CharField(blank=True, default='', help_text='This is variable of the setting.', max_length=254, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=254, verbose_name='Description')),
                ('parameter', models.CharField(blank=True, default='', verbose_name='Parameter')),
                ('sumary_location', models.CharField(blank=True, default='', max_length=254, verbose_name='Location')),
                ('sumary_email', models.CharField(blank=True, default='', max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Sumary',
                'verbose_name_plural': 'Sumaries',
            },
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ('-start_date',), 'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
    ]
