# Generated by Django 5.2 on 2025-04-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sumary_alter_resume_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumary',
            name='name_surname',
            field=models.CharField(blank=True, default='', help_text='This is variable of the setting.', max_length=254, verbose_name='Name Surname'),
        ),
    ]
