# Generated by Django 5.2 on 2025-05-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='Certificate_name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Certificate'),
        ),
    ]
