# Generated by Django 5.2 on 2025-05-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_document_options_remove_document_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ergun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(blank=True, default='', max_length=254, verbose_name='Name')),
                ('parameter', models.CharField(blank=True, default='', verbose_name='Parameter')),
            ],
            options={
                'verbose_name': 'Ergun',
                'verbose_name_plural': 'Erguns',
            },
        ),
    ]
